# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-2019 #'ubuntu-16.04' # 'ubuntu-latest' examples of other options: 'macOS-10.13', 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: config
      nugetConfigPath: NuGet.config

  - task: UseDotNet@2
    inputs:
      version: '3.0.x'
      performMultiLevelLookup: true
      
  - task: UseDotNet@2
    inputs:
      version: '2.2.x'
      packageType: runtime

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
